# Generated by Django 3.0.5 on 2020-04-09 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'CATEGORIA_ITEM',
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14)),
                ('razao_social', models.CharField(max_length=64)),
                ('codigo', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'FORNECEDOR',
            },
        ),
        migrations.CreateModel(
            name='UnidadeMedida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'UNIDADE_MEDIDA',
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=16)),
                ('data', models.DateField(auto_now=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Fornecedor')),
            ],
            options={
                'db_table': 'LOTE',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=16)),
                ('descricao', models.CharField(max_length=128)),
                ('dimensao', models.CharField(max_length=16)),
                ('ativo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CategoriaItem')),
                ('fornecedor', models.ManyToManyField(to='core.Fornecedor')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.UnidadeMedida')),
            ],
            options={
                'db_table': 'ITEM',
            },
        ),
    ]
